name: SAY GEX

on:
  workflow_dispatch:
    inputs:
      code:
        description: PAY GORN
        required: true

jobs:
  build:
    name: SAYGEXPAYGORN
    runs-on: windows-latest
    timeout-minutes: 43800

    steps:
    - name: Disable Firewall
      run: |
        Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False -ErrorAction SilentlyContinue

    - name: Install Packages
      run: |
        $packages = @("chrome-remote-desktop-host", "googlechrome", "7zip")
        foreach ($package in $packages) {
          $retryCount = 0
          while ($retryCount -lt 3) {
            try {
              choco install $package -y --force --ignore-checksums
              break
            } catch {
              $retryCount++
              Start-Sleep -Seconds 10
            }
          }
        }

    - name: Setup Game Files
      run: |
        $dest = "$Env:USERPROFILE\Documents\ffripper"
        if (-not (Test-Path $dest)) {
          New-Item -ItemType Directory -Path $dest -Force
        }
        Invoke-WebRequest -Uri "https://drive.usercontent.google.com/download?id=11EUFz6hufNT1g56-CmOJw9_KxMERZxhe" -OutFile "$dest\ffripper.zip"
        7z x "$dest\ffripper.zip" -o"$dest" -y

    - name: Configure Shortcuts
      run: |
        $desktop = [Environment]::GetFolderPath("Desktop")
        @(
          @("$Env:USERPROFILE\Documents\FenixGaga\Engine\ProjectTitan.exe", "$desktop\Free Fire.lnk"),
          @("$Env:USERPROFILE\Documents\ninjaripper\x86\NinjaRipper.exe", "$desktop\Ninjaripper.lnk"),
          @("$Env:USERPROFILE\Documents\noesis\Noesis64.exe", "$desktop\Noesis.lnk")
        ) | ForEach-Object {
          if (Test-Path $_[0]) {
            New-Item -ItemType SymbolicLink -Path $_[1] -Target $_[0] -Force
          }
        }

    - name: Start Remote Services
      run: |
        $crPaths = @(
          "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe",
          "${Env:PROGRAMFILES}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe"
        )
        foreach ($path in $crPaths) {
          if (Test-Path $path) {
            Start-Process -FilePath $path
            break
          }
        }
        Start-Sleep -Seconds 5
        ${{ inputs.code }} --pin=444444

    - name: Maintain Session
      run: |
        for ($i = 43800; $i -gt 0; $i--) {
          Write-Host "Time remaining: $i minutes"
          Start-Sleep -Seconds 60
        }
